wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.1
    framework: xgboost
    huggingface_version: 4.42.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720697775
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.17.1
      6: 4.42.3
      8:
      - 5
      13: linux-x86_64
